//SEUBARRIGA

describe('SEU BARRIGA', function () {
    beforeEach(function () {
        cy.visit('https://seubarriga.wcaquino.me/login')
    })
    it('COMEÇO- Verifica o título da aplicação', function () {
        cy.title()
            .should('be.equal', 'Seu Barriga - Log in')
    })

    it('Verifica o Titulo de baixo', function () {
        cy.get('a:contains(Seu Barriga)')
            .should('be.visible')
            .click()
    })
    it('Verificar campos antes de fazer um novo cadastro', function () {
        cy.get('a:contains(Novo usuário?)')
            .should('be.visible')
            .click()
        cy.get('label:contains(Nome)')
            .should('be.visible')
        cy.get('label:contains(Email)')
            .should('be.visible')
        cy.get('label:contains(Senha)')
            .should('be.visible')
        cy.contains('.btn', 'Cadastrar')
            .should('be.visible')
    })
    it('Fazer o cadastro', function () {
        cy.get('a:contains(Novo usuário?)')
            .should('be.visible')
            .click()
        cy.get('#nome')
            .type('Eduardo2')
        cy.get('#email')
            .type('user4@user.com')
        cy.get('#senha')
            .type('123')
        cy.contains('.btn', 'Cadastrar')
            .click()
        cy.get('.alert')
            .should('be.visible')
    })
    it.only('Endereço de email já utilizado', function () {
        cy.get('a:contains(Novo usuário?)')
            .should('be.visible')
            .click()
        cy.get('#nome')
            .type('Eduardo2')
        cy.get('#email')
            .type('user4@user.com')
        cy.get('#senha')
            .type('123')
        cy.contains('.btn', 'Cadastrar')
            .click()
        cy.get('.alert')
            .should('be.visible')
        cy.contains('.alert', 'Endereço de email já utilizado')
    })
    it('Usuário inserido com sucesso', function () {
        cy.get('a:contains(Novo usuário?)')
            .should('be.visible')
            .click()
        cy.get('#nome')
            .type('Eduardo2')
        cy.get('#email')
            .type('user4@user.com')
        cy.get('#senha')
            .type('123')
        cy.contains('.btn', 'Cadastrar')
            .click()
        cy.get('.alert')
            .should('be.visible')
        cy.contains('.alert', 'Usuário inserido com sucesso')
    })
})
