uses: cypress-io/github-action@v2
   with:
          config-file: cypress.config.ts
          record: true
          parallel: true
          group: 'UI - Chrome'
          install-command: yarn --immutable
          browser: chrome
          headless: true